### ISSUE TITLE
Further questions

### ISSUE THREAD

**Issue by robotsorcerer** [robustedu/Hexapod-Control#2]
You have rounding operations and subtractions like the one pointed out below splintered throughout your code. What I do not understand is your rationale for doing such.

What were you doing [here](https://github.com/robustedu/Hexapod-Control/blob/master/matlab/appro_r_psi2.m#L7)?

In particular, this `g_psi = g_psi-round(g_psi/2/pi)*2*pi`

YMMV, but I really do think your coding style could use a little more clarity.

**Comment by robustedu** [comment]
I would say that your style of folder structure in coding is better than
mine.

If you feel my code of rounding/subtraction is not good, please feel free
to change it to whatever you like. I completely love to see this. I always
feel happy when I find good coding that I can learn something from it.
To be honest, I love to see my code is improved rather than only
transferred.

**Comment by lakehanne** [comment]
I think what I was trying to pass across was that this statement `g_psi = g_psi-round(g_psi/2/pi)*2*pi` made no sense to me. It is effectively, `g_psi = g_psi-round(g_psi)`. This is not the only place where it is done. I wanted to understand your reason for doing this. Why are you subtracting variables from themselves?

**Comment by robustedu** [comment]
sin(g_psi+2*pi)=sin(g_psi).
Anyway, you can change the code to whatever you feel right. I think there
are more than one way for coding.

**Comment by lakehanne** [comment]
![Figure_1](https://user-images.githubusercontent.com/8429860/67045588-a01a1700-f0fc-11e9-95d8-4221550e971e.png)

**Comment by lakehanne** [comment]
Without rounding in psi from [Qpsi function](https://github.com/robustedu/Hexapod-Control/blob/master/matlab/Q2psi.m#L9), the target errors do not converge. You can verify this by replacing 

`psi = (psi-round(psi/360)*360)/180*pi;`

on line 9 with 
       ```
             psi = (psi)/180*pi;
        ```

![without_psi_rounding](https://user-images.githubusercontent.com/8429860/67148609-4c7c0a80-f26f-11e9-8892-33550f60e5b4.png)


Otherwise, we have

![with_psi_rounding](https://user-images.githubusercontent.com/8429860/67148644-c44a3500-f26f-11e9-89f0-aecb4e105761.png)


The last operation in Q2psi flips the yaw angle to another quadrant on a 360 degrees quadrant chart.

**Comment by robustedu** [comment]
Please change to whatever you think is right. There are more than one way
for coding.
